---
title: "Mini-Project 2: Adventure 2"
author: Jack Tan, Debbie Sun, Alex Denzler, Phuong Nguyen
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
WE ARE CHOOSING TO DO ADVENTURE 2.

```{r, message = FALSE}
library(caret)
library(e1071)
library(dplyr)
library(kernlab)
library(car)
library(openxlsx)
library(VIM)
```


```{r}
kangaroo <- read.csv("https://www.macalester.edu/~ajohns24/data/kangaroo.csv")
#kangaroo_selected <- kangaroo %>%
#  filter(species != c("melanops"))
set.seed(253)
kangaroo_selected <- kangaroo %>% 
  filter(species != c("melanops")) %>%
  mutate_if(is.factor, ~droplevels(.))
levels(kangaroo_selected$species)
```

```{r}
#set the seed
set.seed(253)

#Tuning parameter c
c <- seq(0.01, 3, length = 200)
grid <- expand.grid(sigma = c(.01, .015, 0.2), C = c(0.75, 0.9, 1, 1.1, 1.25))

#svm model
svm_model <- train(
  species ~ zygomatic.width + nasal.width,
  data = kangaroo_selected,
  method = "svmLinear",
  trControl=trainControl(method = "cv", number = 10, selectionFunction = "best"),
  preProcess = c("center", "scale"),
  metric = "Accuracy",
  tuneGrid = data.frame(C = c),
  na.action = na.omit
  )

#svm polynomial model
svm_poly <- train(
  species ~ zygomatic.width + nasal.width,
  data = kangaroo_selected,
  method = "svmPoly",
  trControl=trainControl(method = "cv", number = 10, selectionFunction = "best"),
  preProcess = c("center", "scale"),
  metric = "Accuracy",
  tuneGrid = data.frame(C = c, scale = TRUE, degree = seq(1, 5, length = 5)),
  na.action = na.omit
  )

```


```{r}
plot(svm_model)
plot(svm_poly)
```

```{r}
svm_model$results %>% 
  filter(C == svm_model$bestTune$C)
svm_poly$results %>%
  filter(C == svm_poly$bestTune$C)
```

\
\



## Part 1: Background


\
\
\
\
\
\



## Part 2: 2 predictor analysis


\
\
\
\
\
\



## Part 3: Full analysis




\
\
\
\
\
\



## Part 4: Summarize






\
\
\
\
\
\



## Part 5: Contributions

